matrix:
  include:

    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before-install:
        - npm i -g npm to update
      install:
        - npm install -g jasmine
        - npm install -g jasmine-node
        - jasmine init
        - jasmine examples
      script:
        jasmine

    - language: python
      python: "2.6"
      install:
        - pip install pytest
      script: pytest

    - language: python
      python: "2.7"
      install:
        - pip install pytest
      script: pytest

    - language: python
      python: "3.2"
      install:
        - pip install pytest
      script: pytest

    - language: python
      python: "3.4"
      install:
        - pip install pytest
      script: pytest

    - language: python
      python: "pypy"
      install:
        - pip install pytest
      script: pytest