matrix:
  include:
  - language: node_js
    node_js:
    - iojs
    - '7'
    before-install:
    - npm i -g npm to update
    install:
    - npm install -g jasmine
    - npm install -g jasmine-node
    - jasmine init
    - jasmine examples
    script: jasmine
  - language: python
    python: '2.6'
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: '2.7'
    env: FOO=bar
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: '3.4'
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: pypy
    install:
    - pip install pytest
    script: pytest
  - sudo: required
    language: python
    services: docker
    before_install:
    - docker build -t codesauce/whoisyourbutler .
    - docker ps -aws
    install: pip install pytest
    script: pytest
    after_success:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws ecr get-login --region us-east-1
    - eval $(aws ecr get-login --region us-east-1 --no-include-email)
    - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME"
      -p="$DOCKER_PASSWORD"; docker push codesauce/whoisyourbutler; docker --version;
      docker build -t whoisyourbutler . ; docker tag whoisyourbutler:latest 050429994862.dkr.ecr.us-east-1.amazonaws.com/whoisyourbutler:latest
      ; docker push 050429994862.dkr.ecr.us-east-1.amazonaws.com/whoisyourbutler:latest
      ; fi
env:
  global:
  - secure: oPT+EnnognLRPQXmE3RmZB3/Tf0Qj21HG5+oaybyTHtK3EGm686Xr+d2xzJazayywz2RRZxpmnO3Pt0i5eukvAwM8Tv9AWHj7H7yOSkyearC85f1a0UlGpeqtWtwPJIpLBF+gLVWbHRZsTgf7k1jzQ9eIJ1JNgckCp6FFnEDuyhf/BK5xhSN0WEWwLbWoVhswGDnc90gMVpa6auKs7EN+YHrfJQqY4YWG3b1VGWarmCx60lvG8RP6phsLYN6lXKkPGFe463dCPLpwv5l97Hej5i/gLVduyceli20RsPfSv6CtjvKcKGQZr8989aEvmfawGNjsP+SYmgoWR+qeK3YHqfQTAnjFj3Isdx6M9jgIgp8zle6PO6TFISCGJMAHYzU4k9rD5hXE2xGFcyQEX97b4gnI+9mQ7i07/rGFkCVBqlboy+z90v9KUm8IkjNXkoy62mnfOL5FguIT69upFWNPVIKY9GPSe2C/TaZsswuSBYkM11eqZG/4UbRL6ka3kiJfr1aY3nPi+2pjcxGCywtQpSHegzw7MlSlVfm3YbMkNN4AKVsKfL++egqkzENyB5HvD9qap8RLcsrrjkLQOCTrbeET7ZAJYBH0uu266iUAIhi3UPf6CpCgkw6s6gFnaa5nOvpAbP4lJl8+9z+llVm6YuMczqMNgVdAnVFhFWBcVU=
  - secure: hNrXfTBtb6dtbw0MxtlLQp145ZdXjQMvas6LLffmwoRDZ1ziPIWx9cdjsM7QuDUqMbncRfYd7vEch0m55oXEYXDTAS1qhBPA4cJgCjq2il+3MuOdumKmcRGHPhXfB0+ZS4xtlYHYY1Yr8FRYR3bf9PwO33PZgr9gRTwkuUStxJufVnMKdj/loXsP0Ziej+v8b1eq6wPRNYfX316TMMDkN3yGA1oispjeEqb5KOZwdNal9C+nMBfu2DbLyZMH+MYbXPX4l6SVzj2LNcgiWBDFuf2HIORTnNplw+fH1ARCO8W9ofoTu8qCr94TSyKNPGNici2tFzBaVU/FpGVCT3DRaMGGMsXHGSzkt5YAXW9dK0VmRUmh4Dd96ZWARQ1FfMTBkA6kH9eXIW/227YXEqBJKLWCJFl5QHkD1fu85wHMEmC+LmI2zSZoibS0wwURp6tmleX6KAZbHcDTzX0uRDz0BxdxsPO1EIsDGICI7W3EaSLtDcip2zA27wXwnCcD228WOO4TpVS2naQyTBim4GwOO3/fJILtfegZkPvQJWDQmGhQEnx4QJ6pwWsu9pBCuteBncHFYk71nXq0mKb1jFVH6xeobiBmtvZkbfD2FRRHWzMkC9aVA+18AmJf7wL7yVxEOOndxT6EiTqvyGfc4zesqMlZnWzv7UIqXvzvChExIDc=
deploy:
  provider: s3
  access_key_id: AKIAIZIDUA22TTHDJR4A
  secret_access_key:
    secure: CH8Z3c5jG+2pkSeOK9UHao8efWBpWjhJE7K5qyEv/JADnc4RCWKNEZ4Kde4NWBpSES/HyJcgDd3B2tefk0KNWtdKHncKAvcX0KAQZ9V7ZEHHMfyps6f5gZvFn7+eu1zoyTRaPZY8cDpO12l3PO9GG6DQtftEJZbCl0yvCwnmQlVYdmcHFV2R1OdlPpHs1Sh7U+6ufRI2JVGWrnrTpxYN9TTNp7xiUqtjqm67YtYH3LiVtqhlvXrc97U7pZ7CA12eQ1pkZ403wHbj0lMqCJboQi/+6ZhuV+kUQBC5zhYeNBKMaS8IRiL8BYMIVpWzcdRHoiKoB90CoF/V2531FPR8H9mL/zV1QFgTt6ybDJP0QA8Q0G9WzfmJGdyqqj3HcmqIgGyf95j6w1o+6z9dwfENMpo01dbgvY+9sRR33jJ9Pdp0w1SJcx3y0EsYIfMmppdgEhvVGdpwvIA6tBYM1wWyBXGN2P8KA/rEPPAg+tqpMfrT5TWrzj3u7q/NQiYqjq7FjESLh2oUhY2dHYZzhedKQ44ptxQA8aj1mE/+/tr530fDFsiq1717nVOVhQSYwJAE7QYNSV8rtK9fMftxgQQhnFAPI+0f3a49LJ/hh86DZ+I1o9KkDk9q4CVJOOEK5PUmDeXtF6QvywSGHzazo3EYa1qOfMRZSRViR0lVOCna4C0=
  bucket: whoisyourbutler.deployment
  local-dir: build
  upload-dir: build
  acl: public_read_write
  on:
    repo: code-sauce/whoisyourbutler
notifications:
  slack:
    secure: mX6FMD2GjMuWoxxQSx5Ptu8R77z1WomKK6GMNLlsjLWxasF2Uc4YPT2GsgIAk9bNoWUihlKv6u1A2ho3HADzXR4hghBKJs3lrfhmPK8V10r5655VoeTLzlzDEn337fYaGEZiUc/bikDc0fK3qR/C1vcMZVog7y8fS2h80GXsBqTq+vVxVVYvyTvSiDB87wbzURAZc7tApobysPiEMZRgHxtaK7djliDHfyE6Ho9pMGsmGoaAYbwGsFQvnZh1ZEeacaI9Kx7wohrCTXHf4uK79qQxEd6TD7rR00Scvks1D4KcRxJUiQz5uuyhXeReHGk/4vpU3KUNpOgWEvQKmRS5AW3XfmHoLWCWEYlbSpyzMXJ1GqXIrJi65TrM6vRpMzSNaFEcojVSKaXp3bkWXxveUhKSXcp+Sdwtod9dkWBmti5PdlUdO77MLwRTJ7EY1btiDEtuWBYZWe3s43s+Cxcd2Bsi1PV43tRQC+3hvuL4JSqBor1lp3H1SWu0HxdVwj5RsyfUrItDVoWmYxp+2VOzLyvLzORQ1XnKMZI9lbhLEX7aw/fZFx8A/nT0pm9rikAUlQqfMOji1KH7Z5+YId8kmHdliRkYqMeIuuzeX8FGf1kF1nOH7wtgMpyW/VSbtZhdycuURpe8da7leM002xsNNzL1qUDNIsnYSOAA5cBkVDI=
