matrix:
  include:
  - language: node_js
    node_js:
    - iojs
    - '7'
    before-install:
    - npm i -g npm to update
    install:
    - npm install -g jasmine
    - npm install -g jasmine-node
    - jasmine init
    - jasmine examples
    script: jasmine
  - language: python
    python: '2.6'
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: '2.7'
    env: FOO=bar
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: '3.2'
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: '3.4'
    install:
    - pip install pytest
    script: pytest
  - language: python
    python: pypy
    install:
    - pip install pytest
    script: pytest
  - sudo: required
    language: python
    services: docker
    before_install:
    - docker build -t codesauce/whoisyourbutler .
    - docker ps -a
    install: pip install pytest
    script: pytest
    after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME"
      -p="$DOCKER_PASSWORD"; docker push codesauce/whoisyourbutler; fi
env:
  global:
    secure: oPT+EnnognLRPQXmE3RmZB3/Tf0Qj21HG5+oaybyTHtK3EGm686Xr+d2xzJazayywz2RRZxpmnO3Pt0i5eukvAwM8Tv9AWHj7H7yOSkyearC85f1a0UlGpeqtWtwPJIpLBF+gLVWbHRZsTgf7k1jzQ9eIJ1JNgckCp6FFnEDuyhf/BK5xhSN0WEWwLbWoVhswGDnc90gMVpa6auKs7EN+YHrfJQqY4YWG3b1VGWarmCx60lvG8RP6phsLYN6lXKkPGFe463dCPLpwv5l97Hej5i/gLVduyceli20RsPfSv6CtjvKcKGQZr8989aEvmfawGNjsP+SYmgoWR+qeK3YHqfQTAnjFj3Isdx6M9jgIgp8zle6PO6TFISCGJMAHYzU4k9rD5hXE2xGFcyQEX97b4gnI+9mQ7i07/rGFkCVBqlboy+z90v9KUm8IkjNXkoy62mnfOL5FguIT69upFWNPVIKY9GPSe2C/TaZsswuSBYkM11eqZG/4UbRL6ka3kiJfr1aY3nPi+2pjcxGCywtQpSHegzw7MlSlVfm3YbMkNN4AKVsKfL++egqkzENyB5HvD9qap8RLcsrrjkLQOCTrbeET7ZAJYBH0uu266iUAIhi3UPf6CpCgkw6s6gFnaa5nOvpAbP4lJl8+9z+llVm6YuMczqMNgVdAnVFhFWBcVU=
deploy:
  provider: s3
  access_key_id: AKIAIZIDUA22TTHDJR4A
  secret_access_key:
    secure: PYQWCCknE+n3VYUE7j6Mt8HztyORN7ekVspAPi1V3ScHFMtavhcvzMtArMw83RUjMUf9BSkGnWuxUd+3wBp8c0KCmXW9Y5yZTkjT62ZhYJS79Uv9N5PoJKXFKbnT6hiLOlrRk7wKdyfv152raky25OkUS/QiFnys8cke9h0J27Ok8YBQB2t22KpEXigq3FOF+4+04WvGe19l2zjMUEhuuH+jk46NdBVClKNlRsRujG32ofjYKTQiAhi+6h8T9Vm1maqe9M2R3mOTxNmc0v8MJcDxdbCp2a2/wSU0BKjOLH0jVyDfimpfUXQil2IVmmBTEKxWscbMeIqXwsCdXLQDerQeBydnkLYjx5NaeZcERj/rafr+RzA2caE/Uwly40LxbAzKpKypQENCVFxW4BY+S/RdxkQI5AC24L/37rnNeL0BHuNTSktdJ8CaE/nQyM72aHkeiPIWrEWR+JftvrAy2AW33DnxEzVq5jfJi7xTbQh3yXnYYRBMT4eHLItaY9yh94BWsBnQWBacKvcwWoqrQbMVKzm2xdeZXfYwtMead8yfJltZBy461yTvJeMRwYeXqtISBzdM4XYuME4QsCj43s5l0kYmlLiVxWMiEH6dGiMnWRO2a6kb3hPAkmkYu3Kl67DuTh7F6QXas/9VgqdlGm7LSSZQfThm0u1RqoW6yYo=
  bucket: deployment
  acl: ''
  on:
    repo: code-sauce/whoisyourbutler
