language: node_js
node_js:
  - "iojs"
  - "7"
before-install:
  - npm i -g npm to update
install:
  - npm install -g jasmine
  - npm install -g jasmine-node
  - jasmine init
  - jasmine examples
script:
  jasmine

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest