language: node_js
node_js:
  - "iojs"
  - "7"
before-install:
  - npm i -g npm to update
install:
  - npm install -g jasmine
  - npm install -g jasmine-node
  - jasmine init
  - jasmin examples
script:
  jasmine




