# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# test

version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/python:2.7-jessie-browsers

    working_directory: ~/whoisyourbutler

    steps:
      - checkout
      - run:
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install pytest
      - run:
          command: |
            source venv/bin/activate
            pytest

workflows:
  version: 2
  unittest:
    jobs:
      - build
